import { defineRoutes } from './routes.ts'
import {
  AddProjectRequestSchema,
  AddProjectResponseSchema,
  AgentIdParamsSchema,
  AgentListResponseSchema,
  AgentResponseSchema,
  AgentsSendMessageRequestSchema,
  AgentsUiInterruptResponseSchema,
  AgentsUiSendMessageResponseSchema,
  AgentsUiWorktreeConversationResponseSchema,
  AppConfigSchema,
  AutoNameConfigResponseSchema,
  AvailableBranchesQuerySchema,
  BranchListResponseSchema,
  CancelRunRequestSchema,
  CiLogsResponseSchema,
  CreateRunRequestSchema,
  CreateTabResponseSchema,
  CreateWorktreeRequestSchema,
  CreateWorktreeResponseSchema,
  DiagnosticsResponseSchema,
  EnabledResponseSchema,
  EndpointIdParamsSchema,
  EnvironmentExecRequestSchema,
  EnvironmentExecResponseSchema,
  EnvironmentExposeRequestSchema,
  EnvironmentIdParamsSchema,
  EnvironmentResponseSchema,
  EnvironmentServiceActionRequestSchema,
  EnvironmentServiceParamsSchema,
  EnvironmentServicesResponseSchema,
  EnvironmentTerminalResponseSchema,
  ErrorResponseSchema,
  ExecutionIdParamsSchema,
  ExecutionTranscriptQuerySchema,
  ExecutionTranscriptResponseSchema,
  LinearIssuesResponseSchema,
  NotificationIdParamsSchema,
  OkResponseSchema,
  OpenWorktreeRequestSchema,
  PostWorktreeToLinearRequestSchema,
  PostWorktreeToLinearResponseSchema,
  ProjectIdParamsSchema,
  ProjectInitsResponseSchema,
  ProjectPrefixParamsSchema,
  ProjectSnapshotSchema,
  ProjectsResponseSchema,
  ProjectWorktreeSnapshotSchema,
  PullMainRequestSchema,
  PullMainResponseSchema,
  RemoveWorktreeQuerySchema,
  RespondRunPermissionRequestSchema,
  ResumeRunRequestSchema,
  RunDetailResponseSchema,
  RunEventsQuerySchema,
  RunEventsResponseSchema,
  RunIdParamsSchema,
  RunListResponseSchema,
  RunWorkspaceContextSchema,
  SendWorktreePromptRequestSchema,
  SetWorktreeArchivedRequestSchema,
  SetWorktreeArchivedResponseSchema,
  SetWorktreeLabelRequestSchema,
  SetWorktreeLabelResponseSchema,
  SetWorktreeProfileRequestSchema,
  SetWorktreeProfileResponseSchema,
  TaskflowRunIdParamsSchema,
  ToggleEnabledRequestSchema,
  UpsertCustomAgentRequestSchema,
  ValidateCustomAgentResponseSchema,
  WorkflowListResponseSchema,
  WorktreeDiffResponseSchema,
  WorktreeListResponseSchema,
  WorktreeNameParamsSchema,
  WorktreeTabParamsSchema,
} from './schemas.ts'

export const apiPaths = {
  fetchConfig: '/api/config',
  fetchDiagnostics: '/api/diagnostics',
  fetchEnvironment: '/api/environments/:environmentId',
  fetchEnvironmentServices: '/api/environments/:environmentId/services',
  trustEnvironment: '/api/environments/:environmentId/trust',
  startEnvironment: '/api/environments/:environmentId/start',
  stopEnvironment: '/api/environments/:environmentId/stop',
  restartEnvironment: '/api/environments/:environmentId/restart',
  rebuildEnvironment: '/api/environments/:environmentId/rebuild',
  execEnvironment: '/api/environments/:environmentId/exec',
  openEnvironmentTerminal: '/api/environments/:environmentId/terminal',
  fetchEnvironmentLogs: '/api/environments/:environmentId/logs',
  removeEnvironment: '/api/environments/:environmentId',
  exposeEnvironmentService: '/api/environments/:environmentId/services/:serviceId/expose',
  controlEnvironmentService: '/api/environments/:environmentId/services/:serviceId/action',
  removeEndpoint: '/api/endpoints/:endpointId',
  fetchAvailableBranches: '/api/branches',
  fetchBaseBranches: '/api/base-branches',
  fetchProject: '/api/project',
  fetchAgents: '/api/agents',
  createAgent: '/api/agents',
  updateAgent: '/api/agents/:id',
  deleteAgent: '/api/agents/:id',
  validateAgent: '/api/agents/validate',
  attachAgentsWorktreeConversation: '/api/agents/worktrees/:name/attach',
  fetchAgentsWorktreeConversationHistory: '/api/agents/worktrees/:name/history',
  sendAgentsWorktreeConversationMessage: '/api/agents/worktrees/:name/messages',
  interruptAgentsWorktreeConversation: '/api/agents/worktrees/:name/interrupt',
  streamAgentsWorktreeConversation: '/ws/agents/worktrees/:name',
  fetchWorktrees: '/api/worktrees',
  createWorktree: '/api/worktrees',
  removeWorktree: '/api/worktrees/:name',
  openWorktree: '/api/worktrees/:name/open',
  closeWorktree: '/api/worktrees/:name/close',
  refreshWorktreeAgentTerminal: '/api/worktrees/:name/agent-terminal/refresh',
  setWorktreeArchived: '/api/worktrees/:name/archive',
  syncWorktreePrs: '/api/worktrees/:name/sync-prs',
  postWorktreeToLinear: '/api/worktrees/:name/linear/post',
  setWorktreeLabel: '/api/worktrees/:name/label',
  setWorktreeProfile: '/api/worktrees/:name/profile',
  sendWorktreePrompt: '/api/worktrees/:name/send',
  createWorktreeTab: '/api/worktrees/:name/tabs',
  selectWorktreeTab: '/api/worktrees/:name/tabs/:tabId/select',
  deleteWorktreeTab: '/api/worktrees/:name/tabs/:tabId',
  mergeWorktree: '/api/worktrees/:name/merge',
  fetchWorktreeDiff: '/api/worktrees/:name/diff',
  fetchLinearIssues: '/api/linear/issues',
  fetchAutoNameConfig: '/api/project/auto-name',
  setLinearAutoCreate: '/api/linear/auto-create',
  setAutoRemoveOnMerge: '/api/github/auto-remove-on-merge',
  pullMain: '/api/pull-main',
  fetchCiLogs: '/api/ci-logs/:runId',
  fetchProjectWorkflows: '/api/projects/:projectId/workflows',
  fetchRunWorkspaceContext: '/api/projects/:projectId/run-workspace-context',
  fetchProjectRuns: '/api/projects/:projectId/runs',
  createProjectRun: '/api/projects/:projectId/runs',
  fetchRun: '/api/runs/:runId',
  cancelRun: '/api/runs/:runId/cancel',
  resumeRun: '/api/runs/:runId/resume',
  respondRunPermission: '/api/runs/:runId/permission',
  fetchRunEvents: '/api/runs/:runId/events',
  fetchExecutionTranscript: '/api/executions/:executionId/transcript',
  dismissNotification: '/api/notifications/:id/dismiss',
  fetchProjects: '/api/projects',
  addProject: '/api/projects',
  projectInits: '/api/projects/init',
  removeProject: '/api/projects/:prefix',
} as const

const commonErrorResponses = {
  400: ErrorResponseSchema,
  404: ErrorResponseSchema,
  409: ErrorResponseSchema,
  500: ErrorResponseSchema,
  502: ErrorResponseSchema,
  503: ErrorResponseSchema,
} as const

export const apiContract = defineRoutes({
  fetchConfig: {
    method: 'GET',
    summary: 'Read the dashboard configuration of the project',
    path: apiPaths.fetchConfig,
    responses: {
      200: AppConfigSchema,
    },
  },
  fetchDiagnostics: {
    method: 'GET',
    summary: 'Run the environment readiness checks',
    path: apiPaths.fetchDiagnostics,
    responses: {
      200: DiagnosticsResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  fetchEnvironment: {
    method: 'GET',
    summary: 'Read an execution environment',
    path: apiPaths.fetchEnvironment,
    pathParams: EnvironmentIdParamsSchema,
    responses: { 200: EnvironmentResponseSchema, ...commonErrorResponses },
  },
  fetchEnvironmentServices: {
    method: 'GET',
    summary: 'List the services discovered in an environment',
    path: apiPaths.fetchEnvironmentServices,
    pathParams: EnvironmentIdParamsSchema,
    responses: { 200: EnvironmentServicesResponseSchema, ...commonErrorResponses },
  },
  trustEnvironment: {
    method: 'POST',
    summary: 'Trust an environment configuration and start it',
    path: apiPaths.trustEnvironment,
    pathParams: EnvironmentIdParamsSchema,
    responses: { 200: EnvironmentResponseSchema, ...commonErrorResponses },
  },
  startEnvironment: {
    method: 'POST',
    summary: 'Start an environment',
    path: apiPaths.startEnvironment,
    pathParams: EnvironmentIdParamsSchema,
    responses: { 200: EnvironmentResponseSchema, ...commonErrorResponses },
  },
  stopEnvironment: {
    method: 'POST',
    summary: 'Stop an environment',
    path: apiPaths.stopEnvironment,
    pathParams: EnvironmentIdParamsSchema,
    responses: { 200: EnvironmentResponseSchema, ...commonErrorResponses },
  },
  restartEnvironment: {
    method: 'POST',
    summary: 'Restart an environment',
    path: apiPaths.restartEnvironment,
    pathParams: EnvironmentIdParamsSchema,
    responses: { 200: EnvironmentResponseSchema, ...commonErrorResponses },
  },
  rebuildEnvironment: {
    method: 'POST',
    summary: 'Rebuild an environment',
    path: apiPaths.rebuildEnvironment,
    pathParams: EnvironmentIdParamsSchema,
    responses: { 200: EnvironmentResponseSchema, ...commonErrorResponses },
  },
  execEnvironment: {
    method: 'POST',
    summary: 'Run a command inside an environment',
    path: apiPaths.execEnvironment,
    pathParams: EnvironmentIdParamsSchema,
    body: EnvironmentExecRequestSchema,
    responses: { 200: EnvironmentExecResponseSchema, ...commonErrorResponses },
  },
  openEnvironmentTerminal: {
    method: 'POST',
    summary: 'Describe how to open a terminal in an environment',
    path: apiPaths.openEnvironmentTerminal,
    pathParams: EnvironmentIdParamsSchema,
    responses: { 200: EnvironmentTerminalResponseSchema, ...commonErrorResponses },
  },
  fetchEnvironmentLogs: {
    method: 'GET',
    summary: 'Describe how to follow the logs of an environment',
    path: apiPaths.fetchEnvironmentLogs,
    pathParams: EnvironmentIdParamsSchema,
    responses: { 200: EnvironmentTerminalResponseSchema, ...commonErrorResponses },
  },
  removeEnvironment: {
    method: 'DELETE',
    summary: 'Destroy an environment',
    path: apiPaths.removeEnvironment,
    pathParams: EnvironmentIdParamsSchema,
    responses: { 200: OkResponseSchema, ...commonErrorResponses },
  },
  exposeEnvironmentService: {
    method: 'POST',
    summary: 'Expose an environment service on a private local endpoint',
    path: apiPaths.exposeEnvironmentService,
    pathParams: EnvironmentServiceParamsSchema,
    body: EnvironmentExposeRequestSchema,
    responses: { 200: EnvironmentServicesResponseSchema, ...commonErrorResponses },
  },
  controlEnvironmentService: {
    method: 'POST',
    summary: 'Start, stop or restart an environment service',
    path: apiPaths.controlEnvironmentService,
    pathParams: EnvironmentServiceParamsSchema,
    body: EnvironmentServiceActionRequestSchema,
    responses: { 200: EnvironmentServicesResponseSchema, ...commonErrorResponses },
  },
  removeEndpoint: {
    method: 'DELETE',
    summary: 'Revoke a local endpoint',
    path: apiPaths.removeEndpoint,
    pathParams: EndpointIdParamsSchema,
    responses: { 200: OkResponseSchema, ...commonErrorResponses },
  },
  fetchAvailableBranches: {
    method: 'GET',
    summary: 'List branches that can back a new worktree',
    path: apiPaths.fetchAvailableBranches,
    query: AvailableBranchesQuerySchema,
    responses: {
      200: BranchListResponseSchema,
      400: ErrorResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  fetchBaseBranches: {
    method: 'GET',
    summary: 'List branches that can be used as a base',
    path: apiPaths.fetchBaseBranches,
    responses: {
      200: BranchListResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  fetchProject: {
    method: 'GET',
    summary: 'Read the project snapshot',
    path: apiPaths.fetchProject,
    responses: {
      200: ProjectSnapshotSchema,
      500: ErrorResponseSchema,
      502: ErrorResponseSchema,
    },
  },
  fetchAgents: {
    method: 'GET',
    summary: 'List the configured agents',
    path: apiPaths.fetchAgents,
    responses: {
      200: AgentListResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  createAgent: {
    method: 'POST',
    summary: 'Create a custom agent',
    path: apiPaths.createAgent,
    body: UpsertCustomAgentRequestSchema,
    responses: {
      200: AgentResponseSchema,
      400: ErrorResponseSchema,
      409: ErrorResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  updateAgent: {
    method: 'PUT',
    summary: 'Update a custom agent',
    path: apiPaths.updateAgent,
    pathParams: AgentIdParamsSchema,
    body: UpsertCustomAgentRequestSchema,
    responses: {
      200: AgentResponseSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
      409: ErrorResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  deleteAgent: {
    method: 'DELETE',
    summary: 'Delete a custom agent',
    path: apiPaths.deleteAgent,
    pathParams: AgentIdParamsSchema,
    responses: {
      200: OkResponseSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  validateAgent: {
    method: 'POST',
    summary: 'Validate a custom agent definition',
    path: apiPaths.validateAgent,
    body: UpsertCustomAgentRequestSchema,
    responses: {
      200: ValidateCustomAgentResponseSchema,
      400: ErrorResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  attachAgentsWorktreeConversation: {
    method: 'POST',
    summary: 'Attach the agents UI to a worktree conversation',
    path: apiPaths.attachAgentsWorktreeConversation,
    pathParams: WorktreeNameParamsSchema,
    responses: {
      200: AgentsUiWorktreeConversationResponseSchema,
      ...commonErrorResponses,
    },
  },
  fetchAgentsWorktreeConversationHistory: {
    method: 'GET',
    summary: 'Read the conversation history of a worktree',
    path: apiPaths.fetchAgentsWorktreeConversationHistory,
    pathParams: WorktreeNameParamsSchema,
    responses: {
      200: AgentsUiWorktreeConversationResponseSchema,
      ...commonErrorResponses,
    },
  },
  sendAgentsWorktreeConversationMessage: {
    method: 'POST',
    summary: 'Send a chat message to the agent of a worktree',
    path: apiPaths.sendAgentsWorktreeConversationMessage,
    pathParams: WorktreeNameParamsSchema,
    body: AgentsSendMessageRequestSchema,
    responses: {
      200: AgentsUiSendMessageResponseSchema,
      ...commonErrorResponses,
    },
  },
  interruptAgentsWorktreeConversation: {
    method: 'POST',
    summary: 'Interrupt the running agent turn of a worktree',
    path: apiPaths.interruptAgentsWorktreeConversation,
    pathParams: WorktreeNameParamsSchema,
    responses: {
      200: AgentsUiInterruptResponseSchema,
      ...commonErrorResponses,
    },
  },
  fetchWorktrees: {
    method: 'GET',
    summary: 'List the worktrees of the project',
    path: apiPaths.fetchWorktrees,
    responses: {
      200: WorktreeListResponseSchema,
      500: ErrorResponseSchema,
      502: ErrorResponseSchema,
    },
  },
  createWorktree: {
    method: 'POST',
    summary: 'Create one or more worktrees',
    path: apiPaths.createWorktree,
    body: CreateWorktreeRequestSchema,
    responses: {
      201: CreateWorktreeResponseSchema,
      ...commonErrorResponses,
    },
  },
  removeWorktree: {
    method: 'DELETE',
    summary: 'Remove a worktree',
    path: apiPaths.removeWorktree,
    pathParams: WorktreeNameParamsSchema,
    query: RemoveWorktreeQuerySchema,
    responses: {
      200: OkResponseSchema,
      ...commonErrorResponses,
    },
  },
  openWorktree: {
    method: 'POST',
    summary: 'Open a worktree session',
    path: apiPaths.openWorktree,
    pathParams: WorktreeNameParamsSchema,
    body: OpenWorktreeRequestSchema,
    responses: {
      200: OkResponseSchema,
      ...commonErrorResponses,
    },
  },
  closeWorktree: {
    method: 'POST',
    summary: 'Close a worktree session',
    path: apiPaths.closeWorktree,
    pathParams: WorktreeNameParamsSchema,
    responses: {
      200: OkResponseSchema,
      ...commonErrorResponses,
    },
  },
  refreshWorktreeAgentTerminal: {
    method: 'POST',
    summary: 'Restart the agent terminal of a worktree',
    path: apiPaths.refreshWorktreeAgentTerminal,
    pathParams: WorktreeNameParamsSchema,
    responses: {
      200: OkResponseSchema,
      ...commonErrorResponses,
    },
  },
  setWorktreeArchived: {
    method: 'PUT',
    summary: 'Archive or unarchive a worktree',
    path: apiPaths.setWorktreeArchived,
    pathParams: WorktreeNameParamsSchema,
    body: SetWorktreeArchivedRequestSchema,
    responses: {
      200: SetWorktreeArchivedResponseSchema,
      ...commonErrorResponses,
    },
  },
  postWorktreeToLinear: {
    method: 'POST',
    summary: 'Export a worktree conversation to Linear',
    path: apiPaths.postWorktreeToLinear,
    pathParams: WorktreeNameParamsSchema,
    body: PostWorktreeToLinearRequestSchema,
    responses: {
      200: PostWorktreeToLinearResponseSchema,
      ...commonErrorResponses,
    },
  },
  syncWorktreePrs: {
    method: 'POST',
    summary: 'Refresh the pull request status of a worktree',
    path: apiPaths.syncWorktreePrs,
    pathParams: WorktreeNameParamsSchema,
    responses: {
      200: ProjectWorktreeSnapshotSchema,
      ...commonErrorResponses,
    },
  },
  setWorktreeLabel: {
    method: 'PUT',
    summary: 'Set the label of a worktree',
    path: apiPaths.setWorktreeLabel,
    pathParams: WorktreeNameParamsSchema,
    body: SetWorktreeLabelRequestSchema,
    responses: {
      200: SetWorktreeLabelResponseSchema,
      ...commonErrorResponses,
    },
  },
  setWorktreeProfile: {
    method: 'PUT',
    summary: 'Switch the profile of a worktree',
    path: apiPaths.setWorktreeProfile,
    pathParams: WorktreeNameParamsSchema,
    body: SetWorktreeProfileRequestSchema,
    responses: {
      200: SetWorktreeProfileResponseSchema,
      ...commonErrorResponses,
    },
  },
  sendWorktreePrompt: {
    method: 'POST',
    summary: 'Send a prompt to the agent terminal of a worktree',
    path: apiPaths.sendWorktreePrompt,
    pathParams: WorktreeNameParamsSchema,
    body: SendWorktreePromptRequestSchema,
    responses: {
      200: OkResponseSchema,
      ...commonErrorResponses,
    },
  },
  createWorktreeTab: {
    method: 'POST',
    summary: 'Create a terminal tab in a worktree',
    path: apiPaths.createWorktreeTab,
    pathParams: WorktreeNameParamsSchema,
    responses: {
      201: CreateTabResponseSchema,
      ...commonErrorResponses,
    },
  },
  selectWorktreeTab: {
    method: 'POST',
    summary: 'Select a terminal tab in a worktree',
    path: apiPaths.selectWorktreeTab,
    pathParams: WorktreeTabParamsSchema,
    responses: {
      200: OkResponseSchema,
      ...commonErrorResponses,
    },
  },
  deleteWorktreeTab: {
    method: 'DELETE',
    summary: 'Delete a terminal tab in a worktree',
    path: apiPaths.deleteWorktreeTab,
    pathParams: WorktreeTabParamsSchema,
    responses: {
      200: OkResponseSchema,
      ...commonErrorResponses,
    },
  },
  mergeWorktree: {
    method: 'POST',
    summary: 'Merge a worktree into the main branch',
    path: apiPaths.mergeWorktree,
    pathParams: WorktreeNameParamsSchema,
    responses: {
      200: OkResponseSchema,
      ...commonErrorResponses,
    },
  },
  fetchWorktreeDiff: {
    method: 'GET',
    summary: 'Read the uncommitted diff and unpushed commits of a worktree',
    path: apiPaths.fetchWorktreeDiff,
    pathParams: WorktreeNameParamsSchema,
    responses: {
      200: WorktreeDiffResponseSchema,
      ...commonErrorResponses,
    },
  },
  fetchLinearIssues: {
    method: 'GET',
    summary: 'List the Linear issues assigned to the operator',
    path: apiPaths.fetchLinearIssues,
    responses: {
      200: LinearIssuesResponseSchema,
      500: ErrorResponseSchema,
      502: ErrorResponseSchema,
    },
  },
  fetchAutoNameConfig: {
    method: 'GET',
    summary: 'Read the branch auto-naming configuration',
    path: apiPaths.fetchAutoNameConfig,
    responses: {
      200: AutoNameConfigResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  setLinearAutoCreate: {
    method: 'PUT',
    summary: 'Toggle worktree creation from Linear issues',
    path: apiPaths.setLinearAutoCreate,
    body: ToggleEnabledRequestSchema,
    responses: {
      200: EnabledResponseSchema,
      ...commonErrorResponses,
    },
  },
  setAutoRemoveOnMerge: {
    method: 'PUT',
    summary: 'Toggle worktree removal after a pull request merges',
    path: apiPaths.setAutoRemoveOnMerge,
    body: ToggleEnabledRequestSchema,
    responses: {
      200: EnabledResponseSchema,
      ...commonErrorResponses,
    },
  },
  pullMain: {
    method: 'POST',
    summary: 'Pull the main branch of the project or a linked repository',
    path: apiPaths.pullMain,
    body: PullMainRequestSchema,
    responses: {
      200: PullMainResponseSchema,
      ...commonErrorResponses,
    },
  },
  fetchCiLogs: {
    method: 'GET',
    summary: 'Read the failed logs of a GitHub Actions run',
    path: apiPaths.fetchCiLogs,
    pathParams: RunIdParamsSchema,
    responses: {
      200: CiLogsResponseSchema,
      ...commonErrorResponses,
    },
  },
  fetchProjectWorkflows: {
    method: 'GET',
    summary: 'List the workflows available to a project',
    path: apiPaths.fetchProjectWorkflows,
    pathParams: ProjectIdParamsSchema,
    responses: {
      200: WorkflowListResponseSchema,
      ...commonErrorResponses,
    },
  },
  fetchRunWorkspaceContext: {
    method: 'GET',
    summary: 'Read the checkout state used to start a Run',
    path: apiPaths.fetchRunWorkspaceContext,
    pathParams: ProjectIdParamsSchema,
    responses: {
      200: RunWorkspaceContextSchema,
      ...commonErrorResponses,
    },
  },
  fetchProjectRuns: {
    method: 'GET',
    summary: 'List the Runs of a project',
    path: apiPaths.fetchProjectRuns,
    pathParams: ProjectIdParamsSchema,
    responses: {
      200: RunListResponseSchema,
      ...commonErrorResponses,
    },
  },
  createProjectRun: {
    method: 'POST',
    summary: 'Start a Direct or Workflow Run',
    path: apiPaths.createProjectRun,
    pathParams: ProjectIdParamsSchema,
    body: CreateRunRequestSchema,
    responses: {
      201: RunDetailResponseSchema,
      ...commonErrorResponses,
    },
  },
  fetchRun: {
    method: 'GET',
    summary: 'Read a Run',
    path: apiPaths.fetchRun,
    pathParams: TaskflowRunIdParamsSchema,
    responses: {
      200: RunDetailResponseSchema,
      ...commonErrorResponses,
    },
  },
  cancelRun: {
    method: 'POST',
    summary: 'Cancel a Run',
    path: apiPaths.cancelRun,
    pathParams: TaskflowRunIdParamsSchema,
    body: CancelRunRequestSchema,
    responses: {
      200: RunDetailResponseSchema,
      ...commonErrorResponses,
    },
  },
  resumeRun: {
    method: 'POST',
    summary: 'Resume a Run',
    path: apiPaths.resumeRun,
    pathParams: TaskflowRunIdParamsSchema,
    body: ResumeRunRequestSchema,
    responses: {
      200: RunDetailResponseSchema,
      ...commonErrorResponses,
    },
  },
  respondRunPermission: {
    method: 'POST',
    summary: 'Answer a permission request of a Direct Run',
    path: apiPaths.respondRunPermission,
    pathParams: TaskflowRunIdParamsSchema,
    body: RespondRunPermissionRequestSchema,
    responses: {
      200: RunDetailResponseSchema,
      ...commonErrorResponses,
    },
  },
  fetchRunEvents: {
    method: 'GET',
    summary: 'Replay the events of a Run',
    path: apiPaths.fetchRunEvents,
    pathParams: TaskflowRunIdParamsSchema,
    query: RunEventsQuerySchema,
    responses: {
      200: RunEventsResponseSchema,
      ...commonErrorResponses,
    },
  },
  fetchExecutionTranscript: {
    method: 'GET',
    summary: 'Read the transcript of an execution',
    path: apiPaths.fetchExecutionTranscript,
    pathParams: ExecutionIdParamsSchema,
    query: ExecutionTranscriptQuerySchema,
    responses: {
      200: ExecutionTranscriptResponseSchema,
      ...commonErrorResponses,
    },
  },
  dismissNotification: {
    method: 'POST',
    summary: 'Dismiss a runtime notification',
    path: apiPaths.dismissNotification,
    pathParams: NotificationIdParamsSchema,
    responses: {
      200: OkResponseSchema,
      400: ErrorResponseSchema,
      404: ErrorResponseSchema,
    },
  },
  fetchProjects: {
    method: 'GET',
    summary: 'List the registered projects',
    path: apiPaths.fetchProjects,
    responses: {
      200: ProjectsResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  addProject: {
    method: 'POST',
    summary: 'Register a project',
    path: apiPaths.addProject,
    body: AddProjectRequestSchema,
    responses: {
      200: AddProjectResponseSchema,
      400: ErrorResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  projectInits: {
    method: 'GET',
    summary: 'List project setup records',
    path: apiPaths.projectInits,
    responses: {
      200: ProjectInitsResponseSchema,
      500: ErrorResponseSchema,
    },
  },
  removeProject: {
    method: 'DELETE',
    summary: 'Unregister a project',
    path: apiPaths.removeProject,
    pathParams: ProjectPrefixParamsSchema,
    responses: {
      200: OkResponseSchema,
      404: ErrorResponseSchema,
      500: ErrorResponseSchema,
    },
  },
})
