export const FORWARD_AUTH_MIDDLEWARE = 'portta-forward-auth'
export const AUTH_SERVICE = 'portta-auth'
export const AUTH_PATH_PREFIX = '/__portta/auth'

import type { ProtectionStore } from './protections.ts'

export class UnsafeDynamicValueError extends Error {}

export function quoteDynamicValue(value: string): string {
  if (/["\\\n\r]/.test(value))
    throw new UnsafeDynamicValueError(`refusing to write a value containing quotes or newlines: ${value}`)
  return `"${value}"`
}

function dynamicName(value: string): string {
  return (
    value
      .toLowerCase()
      .replace(/[^a-z0-9-]+/g, '-')
      .replace(/^-+|-+$/g, '')
      .slice(0, 48) || 'protection'
  )
}

function ruleHost(authority: string): string {
  try {
    return new URL(`http://${authority}`).hostname
  } catch {
    return authority
  }
}

/**
 * The shared ForwardAuth service, middleware and unprotected login routers.
 *
 * Projects and shares only. The panel signs people in itself and never passes
 * through this middleware, which is why no scope here is `panel`.
 */
export function renderAuthDynamic(store: ProtectionStore): string {
  const lines = [
    '# ============================================================================',
    '# Generated by Portta. Edits are overwritten.',
    '# ============================================================================',
    '# ForwardAuth is a separate process. The reserved login routers below must',
    '# never reference either authentication middleware. See ADR 0027.',
    '# ============================================================================',
    'http:',
    '  routers:',
  ]
  for (const protection of store.protections) {
    const name = `portta-auth-login-${dynamicName(protection.scope)}`
    lines.push(`    ${name}:`)
    lines.push(
      `      rule: ${quoteDynamicValue(`Host(\`${ruleHost(protection.host)}\`) && PathPrefix(\`${AUTH_PATH_PREFIX}\`)`)}`,
    )
    lines.push(`      entryPoints: [${protection.entryPoints.join(', ')}]`)
    lines.push('      priority: 10000')
    lines.push(`      service: ${AUTH_SERVICE}`)
  }
  lines.push(
    '  services:',
    `    ${AUTH_SERVICE}:`,
    '      loadBalancer:',
    '        servers:',
    `          - url: ${quoteDynamicValue('http://portta-auth:4180')}`,
    '  middlewares:',
    `    ${FORWARD_AUTH_MIDDLEWARE}:`,
    '      forwardAuth:',
    `        address: ${quoteDynamicValue('http://portta-auth:4180/verify')}`,
    '        trustForwardHeader: true',
    '        authResponseHeaders: [X-Forwarded-User, X-Portta-Actor, X-Portta-Actor-Kind]',
    '',
  )
  return lines.join('\n')
}
