// A module's Traefik routes: one generated file per module, written only by
// the panel.
//
// A module that runs on the host (ADR 0047) can produce a service worth a URL —
// an app on a Dev Container port, a preview a workflow started. It may not
// answer for that URL itself: a second gateway would mean two processes
// listening for the same hostnames, and a module writing Traefik configuration
// would be a second writer outside the panel's allowlist.
//
// So the module reports what it has, and the panel renders it here.
// See docs/development/adr/0048-module-endpoints-through-traefik.md.

import { FORWARD_AUTH_MIDDLEWARE, quoteDynamicValue, UnsafeDynamicValueError } from './dynamic.ts'

/** How a module endpoint is reached, and whether anyone may reach it. */
export interface StoredModuleEndpoint {
  /** Unique within the module. Becomes part of a Traefik router name. */
  id: string
  /** The full hostname, already derived by the ADR 0023 rules. */
  host: string
  entryPoint: string
  /**
   * An address the gateway network can dial — a container name, or a host the
   * Traefik container resolves. A loopback address of the host is not one:
   * Traefik runs in a container and would reach its own loopback instead.
   */
  target: string
  port: number
  scheme?: 'http' | 'https'
  /** `protected` carries ForwardAuth. `public` is an explicit operator decision. */
  mode: 'public' | 'protected'
}

export const MODULE_ENDPOINTS_MARKER = '# portta-module-endpoints: '

/** `portta-module-<id>.yaml`, the module's whole write surface. */
export function moduleEndpointsFile(moduleId: string): string {
  return `portta-module-${moduleId}.yaml`
}

export function moduleRouterName(moduleId: string, endpointId: string): string {
  return `portta-module-${moduleId}-${endpointId}`
}

/**
 * Router names end up as YAML keys and Traefik identifiers, so they are
 * constrained here rather than trusted. An id that would need escaping is a
 * caller's bug, and refusing it is cheaper than discovering a broken router
 * after Traefik reloaded.
 */
const SAFE_NAME = /^[a-z0-9][a-z0-9-]*$/

function assertSafeName(value: string, what: string): void {
  if (!SAFE_NAME.test(value)) {
    throw new UnsafeDynamicValueError(`${what} must be lowercase alphanumeric with dashes: ${value}`)
  }
}

const HEADER = [
  '# ============================================================================',
  '# Generated by Portta panel. Edits are overwritten.',
  '# ============================================================================',
  "# A module's endpoints: one router per service a module asked to publish.",
  '# The module never writes here; revoking an endpoint rewrites this file',
  '# without it, and switching the module off removes the file entirely.',
  '# See docs/development/adr/0048-module-endpoints-through-traefik.md.',
  '# ============================================================================',
]

/** The canonical renderer for a module's routes. Empty input renders an empty file, not a stale one. */
export function renderModuleEndpoints(moduleId: string, endpoints: readonly StoredModuleEndpoint[]): string {
  assertSafeName(moduleId, 'module id')
  for (const endpoint of endpoints) assertSafeName(endpoint.id, 'endpoint id')

  const seen = new Set<string>()
  for (const endpoint of endpoints) {
    if (seen.has(endpoint.id)) throw new UnsafeDynamicValueError(`duplicate endpoint id: ${endpoint.id}`)
    seen.add(endpoint.id)
  }

  const lines = [...HEADER, `${MODULE_ENDPOINTS_MARKER}${JSON.stringify(endpoints)}`, '']
  if (endpoints.length === 0) {
    lines.push('# This module publishes nothing. Absence of a router is how that is said.')
    return `${lines.join('\n')}\n`
  }

  lines.push('http:', '  routers:')
  for (const endpoint of endpoints) {
    const router = moduleRouterName(moduleId, endpoint.id)
    lines.push(`    ${router}:`)
    lines.push(`      rule: ${quoteDynamicValue(`Host(\`${endpoint.host}\`)`)}`)
    lines.push(`      entryPoints: [${endpoint.entryPoint}]`)
    if (endpoint.mode === 'protected') lines.push(`      middlewares: [${FORWARD_AUTH_MIDDLEWARE}]`)
    lines.push(`      service: ${router}`)
  }

  lines.push('  services:')
  for (const endpoint of endpoints) {
    const router = moduleRouterName(moduleId, endpoint.id)
    const scheme = endpoint.scheme ?? 'http'
    lines.push(`    ${router}:`, '      loadBalancer:', '        servers:')
    lines.push(`          - url: ${quoteDynamicValue(`${scheme}://${endpoint.target}:${endpoint.port}`)}`)
  }

  lines.push('')
  return lines.join('\n')
}

/** Reads back what the panel itself wrote, so a restart does not lose the set. */
export function parseModuleEndpoints(contents: string | null): StoredModuleEndpoint[] {
  if (!contents) return []
  const line = contents.split('\n').find((entry) => entry.startsWith(MODULE_ENDPOINTS_MARKER))
  if (!line) return []
  try {
    const parsed: unknown = JSON.parse(line.slice(MODULE_ENDPOINTS_MARKER.length))
    if (!Array.isArray(parsed)) return []
    return parsed.filter((entry): entry is StoredModuleEndpoint => {
      const value = entry as Record<string, unknown>
      return typeof value?.id === 'string' && typeof value?.host === 'string' && typeof value?.target === 'string'
    })
  } catch {
    return []
  }
}
