// Passwords generated by the gateway and the one hash format Portta owns.

import { scrypt as nodeScrypt, randomBytes, randomInt, timingSafeEqual } from 'node:crypto'

/** No 0, 1, I or O: this password is read aloud and typed by hand. */
const ALPHABET = '23456789ABCDEFGHJKLMNPQRSTUVWXYZ'
const SCRYPT_PREFIX = '$portta$scrypt$'
const SCRYPT_N = 65_536
const SCRYPT_R = 8
const SCRYPT_P = 1
const SCRYPT_KEY_LENGTH = 32
const SCRYPT_MAX_MEMORY = 96 * 1024 * 1024
function scryptPassword(
  password: string,
  salt: Buffer,
  length: number,
  options: { N: number; r: number; p: number; maxmem: number },
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    nodeScrypt(password, salt, length, options, (error, derived) => {
      if (error) reject(error)
      else resolve(derived)
    })
  })
}

/**
 * A password worth generating: 20 characters over a 32-symbol alphabet, which
 * is 100 bits. Grouped with dashes because it gets copied by hand.
 */
export function generatePassword(groups = 4, size = 5): string {
  const parts: string[] = []
  for (let group = 0; group < groups; group += 1) {
    let chunk = ''
    for (let index = 0; index < size; index += 1) chunk += ALPHABET[randomInt(ALPHABET.length)]
    parts.push(chunk)
  }
  return parts.join('-')
}

function equal(left: Buffer, right: Buffer): boolean {
  return left.length === right.length && timingSafeEqual(left, right)
}

/** Hash a newly supplied password with the one format Portta owns. */
export async function hashPassword(password: string): Promise<string> {
  const salt = randomBytes(16)
  const derived = await scryptPassword(password, salt, SCRYPT_KEY_LENGTH, {
    N: SCRYPT_N,
    r: SCRYPT_R,
    p: SCRYPT_P,
    maxmem: SCRYPT_MAX_MEMORY,
  })
  return `${SCRYPT_PREFIX}${SCRYPT_N}$${SCRYPT_R}$${SCRYPT_P}$${salt.toString('base64url')}$${derived.toString('base64url')}`
}

async function verifyScrypt(password: string, encoded: string): Promise<boolean> {
  const parts = encoded.split('$')
  if (parts.length !== 8 || parts[1] !== 'portta' || parts[2] !== 'scrypt') return false
  const n = Number(parts[3])
  const r = Number(parts[4])
  const p = Number(parts[5])
  if (n !== SCRYPT_N || r !== SCRYPT_R || p !== SCRYPT_P) return false
  const salt = Buffer.from(parts[6] ?? '', 'base64url')
  const wanted = Buffer.from(parts[7] ?? '', 'base64url')
  if (salt.length !== 16 || wanted.length !== SCRYPT_KEY_LENGTH) return false
  const actual = await scryptPassword(password, salt, wanted.length, { N: n, r, p, maxmem: SCRYPT_MAX_MEMORY })
  return equal(actual, wanted)
}

/** Verify the single hash format Portta writes. */
export async function verifyPassword(password: string, encoded: string): Promise<boolean> {
  try {
    return encoded.startsWith(SCRYPT_PREFIX) && (await verifyScrypt(password, encoded))
  } catch {
    return false
  }
}
