// This installation, and what the operator configured on it.

import { sql } from 'drizzle-orm'
import { check, sqliteTable, text } from 'drizzle-orm/sqlite-core'
import { createdAt, flag, json, updatedAt } from './columns.ts'

/**
 * One row, forever. `singleton` is unique and checked true, so a second insert
 * conflicts rather than quietly producing a second identity.
 *
 * The id is a UUID in a `text` column. SQLite has no uuid type and no
 * `gen_random_uuid()`, so the value is generated by the driver — which is where
 * it always came from in practice, since the panel reads the id back.
 */
export const instance = sqliteTable(
  'instance',
  {
    id: text('id')
      .primaryKey()
      .$defaultFn(() => crypto.randomUUID()),
    singleton: flag('singleton').notNull().default(true).unique(),
    name: text('name').notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (table) => [
    check('instance_singleton_check', sql`${table.singleton} = 1`),
    check('instance_name_check', sql`trim(${table.name}) <> ''`),
  ],
)

/**
 * The operator's settings, as a closed catalogue: the keys and their shapes are
 * declared in packages/server/src/services/settings.ts, and a value that does
 * not match its schema is read as absent rather than trusted.
 */
export const settings = sqliteTable(
  'settings',
  {
    key: text('key').primaryKey(),
    value: json<unknown>('value').notNull(),
    updatedAt: updatedAt(),
  },
  (table) => [check('settings_key_check', sql`trim(${table.key}) <> ''`)],
)
